### ISSUE TITLE
[Bug]: Rocket Scanner Bug

### ISSUE THREAD

**Issue by openblocki** [Argent-Matter/gcys#59] opened 2024-10-21 17:58 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None other than GCYR and GTCEU

### Expected Behavior

Rocket Scanner UI should be completely Visible and Interactable like back when it worked 

### Actual Behavior

UI looks Cut off early. 
![2024-10-21_19 57 07](https://github.com/user-attachments/assets/ef861467-449f-42b0-9254-d60ed119ff77)

### Steps to Reproduce

1. Place Rocket Scanner.
2. Interact with / Open Rocket Scanner.

**Comment by screret** [comment] 2024-10-21 18:09
duplicate of #57

**Closed as completed by screret** 2024-10-21 18:09 UTC
Labels: bug
