### ISSUE TITLE
Newest Version Incompatible with GTCEu 1.0.20+ using Forge-47.2.19

### ISSUE THREAD

**Issue by SeSarigGod** [Argent-Matter/gcys#10] opened 2024-01-08 01:43 UTC
[debug.log](https://github.com/Argent-Matter/gcyr/files/13855577/debug.log)
[latest.log](https://github.com/Argent-Matter/gcyr/files/13855578/latest.log)
[crash-2024-01-07_19.34.22-client.txt](https://github.com/Argent-Matter/gcyr/files/13855579/crash-2024-01-07_19.34.22-client.txt)

Version 0.1.2.c

**Comment by SeSarigGod** [comment] 2024-01-09 03:49
[debug.log](https://github.com/Argent-Matter/gcyr/files/13868603/debug.log)
[latest.log](https://github.com/Argent-Matter/gcyr/files/13868604/latest.log)
[crash-2024-01-08_21.47.59-client.txt](https://github.com/Argent-Matter/gcyr/files/13868605/crash-2024-01-08_21.47.59-client.txt)

Version 0.1.3-aa

**Comment by screret** [comment] 2024-01-18 14:23
duplicate of #13.

**Closed as completed by screret** 2024-01-18 14:23 UTC
