### ISSUE TITLE
Rocket assembly machine GUI is broken 

### ISSUE THREAD

**Issue by FlatterSHEE** [Argent-Matter/gcys#61] opened 2024-10-25 15:50 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtcu-1.20.1-1.4.6

### Recipe Viewer Installed

EMI

### Environment

Singlplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

monifactory 0.9.10

### Expected Behavior

Expected to get to build a rocket, but the GUI of the Rocket Scanner is broken (screenshot in the attachments)
![Rocket Scanner Bug report 2](https://github.com/user-attachments/assets/3a1f5bca-0000-48d6-bb65-3df37e18166c)
![Rocket Scanner Bug report 1](https://github.com/user-attachments/assets/e5a2b790-0c63-4364-b805-dd831349bba9),
The bug has been observed previously by other players and reported to the monifactory github page, from where they've been redirected to the mod authors

### Actual Behavior

Broken GUI, can't assemble the rocket 

### Steps to Reproduce

Step1. install monifactory 0.9.10
Step2. build rocket scanner multiblock structure
Step 3. Open rocket scanner GUI 
Step.4 Bug should be observable

**Comment by screret** [comment] 2024-10-25 15:57
duplicate of #57

**Closed as completed by screret** 2024-10-25 15:57 UTC
Labels: bug
