### ISSUE TITLE
Rocker Scanner UI - Not Visible

### ISSUE THREAD

**Issue by kwbrooks373** [Argent-Matter/gcys#62] opened 2024-10-30 18:06 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Recipe Viewer Installed

EMI

### Environment

SinglePlayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

MoniFactory version 0.9.10- Modpack. No Resourepack installed.

### Expected Behavior

When I open Rocket Scanner I expect to see a GUI to scan / build rocket.

### Actual Behavior

![Interface](https://github.com/user-attachments/assets/08de3996-b903-437d-9fdc-d5ffbe883eed)

Interface has a panel that is blocking the text / interface

### Steps to Reproduce

I created a new world in creative mode. Removed all resource packs, using only Monifactory Modpack.
I added the launch pad, Stainless Steel Frames, and then placed the Rocket Scanner. Rocket Scanner says structure / multiblock created. When I right click to open interface, I can't interact with the GUI. See attached screenshot in the 'Actual Behavior' section.

**Comment by screret** [comment] 2024-10-30 18:41
duplicate of #57

**Closed as completed by screret** 2024-10-30 18:41 UTC
Labels: bug
